apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: iresizer
  name: readonly-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: readonly-binding
  namespace: iresizer
subjects:
- kind: User
  name: dimzrio
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: readonly-role
  apiGroup: rbac.authorization.k8s.io