apiVersion: v1
kind: ServiceAccount
metadata:
  name: dimzrio-sa
  namespace: applications

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: readonly-role
  namespace: applications
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: readonly-binding
  namespace: applications
subjects:
- kind: ServiceAccount
  name: dimzrio-sa
  namespace: applications
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: readonly-role