apiVersion: v1
kind: Pod
metadata:
  name: nginx-brustable
  namespace: applications
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    resources:
      requests:
        cpu: "500m"
        memory: "128Mi"
    ports:
      - containerPort: 80