apiVersion: v1
kind: Pod
metadata:
  name: webserver
  labels:
    name: webserver
spec:
  containers:
    - name: nginx
      image: nginx:alpine
      resources:
        requests:
          memory: "64Mi"
          cpu: "128m"
        limits:
          memory: "128Mi"
          cpu: "256m"
      ports:
        - containerPort: 80
    - name: tomcat
      image: tomcat:latest
      resources:
        requests:
          memory: "64Mi"
          cpu: "128m"
        limits:
          memory: "128Mi"
          cpu: "256m"
      ports:
        - containerPort: 8080