kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: developer-role
  namespace: development
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["pods", "deployments", "replicasets"]
  verbs: ["*"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: developer-binding
  namespace: development
subjects:
- kind: User
  name: devel
  apiGroup: rbac.authorization.k8s.io
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: developer-role