kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: readonly-role
  namespace: applications
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]

# Full Permission for pods, deployment & replicasets
# - apiGroups: ["", "extensions", "apps"]
#   resources: ["pods", "deployments", "replicasets"]
#   verbs: ["*"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: readonly-rolebinding
  namespace: applications
subjects:
- kind: User
  name: readonly
  apiGroup: rbac.authorization.k8s.io
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: readonly-role