apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-env
  namespace: applications
data:
  APPS_ENV: productions
  APPS_VERSION: v1.0.0
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-vhost
  namespace: applications
data:
  default.conf: |
    server {
      listen 80;
      server_name _;
      root /public_html;

      location / {
        index index.html;
      }
    }
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index
  namespace: applications
data:
  index.html: |
    <html>
    <body>
    <p> This is an example configmap </p>
    </body>
    </html>
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  namespace: applications
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        envFrom:
          - configMapRef:
              name: nginx-env
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
          - mountPath: /etc/nginx/conf.d
            readOnly: true
            name: vhost
          - mountPath: /public_html
            readOnly: true
            name: index
        ports:
        - containerPort: 80
      volumes:
        - name: vhost
          configMap:
            name: nginx-vhost
            items:
              - key: default.conf
                path: default.conf   
        - name: index
          configMap:
            name: nginx-index
            items:
              - key: index.html
                path: index.html