apiVersion: batch/v1
kind: Job
metadata:
  name: greeting
  namespace: applications
spec:
  completions: 5
  parallelism: 2
  template:
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["echo", "Hello Kubernetes!!!"]
      restartPolicy: Never