apiVersion: v1
kind: Pod
metadata:
  name: nginx-pods
  namespace: applications
  labels:
    name: webserver
spec:
  containers:
    - name: nginx
      image: nginx:alpine
      resources:
        requests:
          memory: "64Mi"
          cpu: "128m"
        limits:
          memory: "128Mi"
          cpu: "256m"
      ports:
        - containerPort: 80
  nodeSelector:
    kubernetes.io/hostname: centz3

# $ kubectl get all -n applications -o wide
# NAME             READY     STATUS    RESTARTS   AGE       IP             NODE
# pod/nginx-pods   1/1       Running   0          2s        10.233.85.47   centz3