apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-01
  labels:
    name: http
spec:
  containers:
    - name: http
      image: nginx:alpine
      resources:
        requests:
          memory: "64Mi"
          cpu: "128m"
        limits:
          memory: "128Mi"
          cpu: "256m"
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: /data
          name: data
  volumes:
  - name: data
    emptyDir: {}