apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-02
  labels:
    name: http
spec:
  containers:
    - name: http
      image: nginx:alpine
      resources:
        requests:
          memory: "64Mi"
          cpu: "128m"
          ephemeral-storage: "1Gi"
        limits:
          memory: "128Mi"
          cpu: "256m"
          ephemeral-storage: "2Gi"
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: /data
          name: tmpfs
  volumes:
  - name: tmpfs
    emptyDir:
      medium: "Memory"