apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: webserver-rs
  namespace: applications
  labels:
    app: webserver
spec:
  replicas: 2
  selector:
    matchExpressions:
      - { key: app, operator: In, values: [webserver, nginx-services] }
  template:
    metadata:
      name: nginx
      labels:
        app: nginx-services
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: webserver-clusterip-services
  namespace: applications
spec:
  selector:
    app: nginx-services
  ports:
  - port: 80
    targetPort: 80