apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-storage
  namespace: applications
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: localstorage
  resources:
    requests:
      storage: 2Gi