apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  namespace: applications
  labels:
    name: mongo
spec:
  containers:
  - name: mongo
    image: mongo:4.0
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 27017
    volumeMounts:
      - name: mongo-datastore
        mountPath: /data/db
  volumes:
    - name: mongo-datastore
      persistentVolumeClaim:
        claimName: local-storage