apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-storage
  namespace: applications
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: localstorage
  hostPath:
    path: /mnt/pvdevices
    type: DirectoryOrCreate