apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  namespace: applications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-web-server
  template:
    metadata:
      labels:
        app: nginx-web-server
    spec:
      volumes:
      - name: document-root
        hostPath:
          path: /public_html
          type: Directory
      containers:
      - name: nginx
        image: nginx:alpine
        resources:
          requests:
            memory: "128Mi"
            cpu: 500m
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: document-root
        ports:
        - containerPort: 80