apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: nginx-rs
  namespace: applications
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      name: nginx
      labels:
        app: webserver
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80