apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-volume
spec:
  volumes:
  - name: www
  containers:
  - name: nginx
    image: nginx:latest
    resources:
      requests:
        memory: "64Mi"
        cpu: "128m"
      limits:
        memory: "128Mi"
        cpu: "256m"
    volumeMounts:
    - name: www
      mountPath: /usr/share/nginx/html/

  - name: curl
    image: alpine:latest
    resources:
      requests:
        memory: "64Mi"
        cpu: "128m"
      limits:
        memory: "128Mi"
        cpu: "256m"
    command: [ "sh", "-c", "apk add --no-cache curl && curl http://example.com/ > /www/index.html" ]
    volumeMounts:
    - name: www
      mountPath: /www/
  restartPolicy: OnFailure