# Bind service account to cluster-admin Cluster Role
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: applications-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: applications-sa
  namespace: applications
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: kubernetes

---

# Bind service account default & applicastions-sa in namespace applications to admin cluster role 
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: applications-rolebinding
  namespace: applications
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: applications-sa
  namespace: applications
- kind: ServiceAccount
  name: default
  namespace: applications