apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: greeting
  namespace: applications
spec:
  schedule: "* * * * *"  # Run every minute
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: busybox
            image: busybox
            command: ["date"]
          restartPolicy: Never