apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver-deploy
  namespace: applications
  labels:
    app: webserver-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-deploy
  template:
    metadata:
      labels:
        app: nginx-deploy
    spec:
      volumes:
      - name: document-root
        hostPath:
          path: /public_html
          type: Directory
      containers:
      - name: nginx
        image: nginx:alpine
        resources:
          requests:
            memory: "128Mi"
            cpu: 500m
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: document-root
        ports:
        - containerPort: 80

# $ kubectl get all -n applications -o wide

# NAME                                    READY     STATUS    RESTARTS   AGE       IP              NODE
# pod/webserver-deploy-78f9dd7454-mgzgq   1/1       Running   0          7m        10.233.102.50   centz4

# NAME                               DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE       CONTAINERS   IMAGES         SELECTOR
# deployment.apps/webserver-deploy   1         1         1            1           7m        nginx        nginx:alpine   app=nginx-deploy

# NAME                                          DESIRED   CURRENT   READY     AGE       CONTAINERS   IMAGES         SELECTOR
# replicaset.apps/webserver-deploy-78f9dd7454   1         1         1         7m        nginx        nginx:alpine   app=nginx-deploy,pod-template-hash=78f9dd7454