apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver-deploy
  namespace: applications
  labels:
    app: webserver-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-deploy
  template:
    metadata:
      labels:
        app: nginx-deploy
    spec:
      volumes:
      - name: document-root
        hostPath:
          path: /public_html
          type: Directory
      containers:
      - name: nginx
        image: nginx:alpine
        resources:
          requests:
            memory: "128Mi"
            cpu: 500m
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: document-root
        ports:
        - containerPort: 80