---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: iresizer-sa
  namespace: iresizer
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: iresizer
  name: iresier-role
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["apps"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["extensions"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["autoscaling"]
  resources: ["*"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: iresizer-rolebinding
  namespace: iresizer
subjects:
- kind: ServiceAccount
  name: iresizer-sa
  namespace: iresizer
roleRef:
  kind: Role
  name: iresizer-role
  apiGroup: rbac.authorization.k8s.io