apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: applications
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    resources:
      requests:
        cpu: "500m"
        memory: "600Mi"
    ports:
      - containerPort: 80