apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: applications
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    resources:
      requests:
        memory: "20Mi"
      limits:
        memory: "1.5Gi"
    ports:
      - containerPort: 80