apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: applications
type: Opaque
data:
  username: YWRtaW4=
  password: ZGltenJpbzEyMw==

---

apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  namespace: applications
  labels:
    name: db
spec:
  containers:
  - name: mongo
    image: mongo:4.0
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 27017
    env:
      - name: MONGO_INITDB_ROOT_USERNAME
        valueFrom:
          secretKeyRef:
            name: mongo-secret
            key: username
      - name: MONGO_INITDB_ROOT_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mongo-secret
            key: password