apiVersion: v1
kind: Pod
metadata:
  name: nginx-pods
  labels:
    name: http
spec:
  containers:
    - name: web1
      image: nginx:alpine
      resources:
        requests:
          memory: "64Mi"
          cpu: "128m"
        limits:
          memory: "128Mi"
          cpu: "256m"
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: /demo
          name: shared-data

    - name: web2
      image: tomcat:latest
      resources:
        requests:
          memory: "64Mi"
          cpu: "128m"
        limits:
          memory: "128Mi"
          cpu: "256m"
      ports:
        - containerPort: 8080
      volumeMounts:
        - mountPath: /demo
          name: shared-data
  volumes:
  - name: shared-data
    emptyDir: {}